model:
  output_model_path: model/weights
  output_results_path: model/results
  dataset_path: data/TUDataset
  dataset: ENZYMES
  nb_of_splits: 10  # Number of times the model is going to be trained on shuffled data in order to average the test value at the end
  verbose: 1
  max_epochs: 200
  patience: 20
  device: 
  lr: 0.005
  hidden_channels: 64
  convolution_layer: GCN
  attention_heads: 4
  global_pooling_layer: mean
  local_pooling_layer:
  alpha: 1e-2
  batch_size: 64
  deterministic_algorithms: True

