model:
  model_name: test
  output_model_path: model/weights
  output_results_path: model/results
  dataset_path: data/TUDataset
  dataset: MUTAG
  nb_of_trainings: 3  # Number of times the model is going to be trained on shuffled data in order to average the test value at the end
  verbose: 1
  max_epochs: 200
  patience: 20
  device:
  lr: 0.005
  hidden_channels: 64
  convolution_layer: GCN
  global_pooling_layer: mean
  local_pooling_layer: SAG